server:
  port:  7900
  address: 127.0.0.1
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8  


  

 
logging:
  level:
    root : INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
    
    
  